# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbc18bac723244bfd7158dd7b9a7ffeb8e61e595a0d6914d2b9f0a4e58b81985c4633ae4179a1120206f97753cb10ed6ec8be46de3f6a7e7a1a62d47434b6884

test:
  secret_key_base: d17ad2368e578a573e568bb8d786f28402313b658db0d5c8299ea760844cd6f35f75438a73b3dc615597546aed30e1b63046f26da20a2d2acbc2cc92570ca28c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
